version: '3.8'
services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "15432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
  api:
    container_name: api
    build: .
    environment:
      - DATABASE_URL =  db
    depends_on:
      - db
